apiVersion: v2
name: kas
description: k8s agent server
version: 0.3.1
appVersion: "0.2.0"
dependencies:
  - name: redis
    version: 24.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
