apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kas.fullname" . }}
  labels:
    {{- include "kas.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- if eq "nginx" $.Values.ingress.ingressClass }}
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/custom-http-errors: ""
    nginx.ingress.kubernetes.io/backend-protocol: https
    {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClass }}
  rules:
    - host: {{ .Values.ingress.kas_dns | quote }}
      http:
        paths:
          - path: "{{ $.Values.ingress.kubernetesApiPath }}"
            pathType: Prefix
            backend:
              service:
                name: {{ include "kas.serviceName" . }}
                port:
                  number: {{ .Values.service.kubernetesApiPort }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "kas.serviceName" . }}
                port:
                  number: {{ .Values.service.externalPort }}
  tls:
    - hosts:
        - {{ .Values.ingress.kas_dns | quote }}
      secretName: {{ .Values.ingress.tlsSecretName }}