apiVersion: v2
name: kas
description: k8s agent server
version: 0.0.0
appVersion: "0.0.0"
dependencies:
  - name: redis
    version: 18.1.6
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled