# permissions for end users to view upgradeplancallouts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: upgradeplancallout-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controller
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
  name: upgradeplancallout-viewer-role
rules:
- apiGroups:
  - deployments.plural.sh
  resources:
  - upgradeplancallouts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deployments.plural.sh
  resources:
  - upgradeplancallouts/status
  verbs:
  - get
