apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: console
  labels:
{{ include "console.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClass }}
  {{ if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.console_dns | quote }}
    secretName: console-tls
  {{ end }}
  rules:
  - host: {{ .Values.ingress.console_dns | quote }}
    http:
      paths:
      {{ if .Values.dashboard.enabled }}
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ template "kubernetes-dashboard.fullname" .Subcharts.dashboard }}-{{ .Values.dashboard.api.role }}
            port:
              name: {{ .Values.dashboard.api.role }}
      {{ end }}
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: console
            port: 
              name: http
{{ if .Values.externalIngress.hostname }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: console-external
  labels:
{{ include "console.labels" . | indent 4 }}
  {{- with .Values.externalIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.externalIngress.ingressClass }}
  tls:
  - hosts:
    - {{ .Values.externalIngress.hostname | quote }}
    secretName: console-external-tls
  rules:
  - host: {{ .Values.externalIngress.hostname | quote }}
    http:
      paths:
      - path: /ext
        pathType: Prefix
        backend:
          service: 
            name: console
            port: 
              name: http
{{ end }}
