{{- if .Values.nexus.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: nexus-config
  labels:
    {{- include "console.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
{{ toYaml .Values.nexus.config | indent 4 }}
{{- end }}
