versions:
- version: 1.9.4
  kube: ['1.28', '1.27', '1.26', '1.25']
  requirements: []
  incompatibilities: []
- version: 1.9.3
  kube: ['1.28', '1.27', '1.26', '1.25']
  requirements: []
  incompatibilities: []
- version: 1.9.1
  kube: ['1.28', '1.27', '1.26', '1.25']
  requirements: []
  incompatibilities: []
- version: 1.9.0
  kube: ['1.28', '1.27', '1.26', '1.25']
  requirements: []
  incompatibilities: []
- version: 1.8.4
  kube: ['1.27', '1.26', '1.25', '1.24']
  requirements: []
  incompatibilities: []
- version: 1.8.2
  kube: ['1.27', '1.26', '1.25', '1.24']
  requirements: []
  incompatibilities: []
- version: 1.8.1
  kube: ['1.27', '1.26', '1.25', '1.24']
  requirements: []
  incompatibilities: []
- version: 1.8.0
  kube: ['1.27', '1.26', '1.25', '1.24']
  requirements: []
  incompatibilities: []
- version: 1.7.1
  kube: ['1.27', '1.26', '1.25', '1.24']
  requirements: []
  incompatibilities: []
- version: 1.7.0
  kube: ['1.26', '1.25', '1.24']
  requirements: []
  incompatibilities: []
- version: 1.6.4
  kube: ['1.26', '1.25', '1.24', '1.23']
  requirements: []
  incompatibilities: []
- version: 1.5.1
  kube: ['1.25', '1.24', '1.23']
  requirements: []
  incompatibilities: []
- version: 1.4.0
  kube: ['1.25', '1.24', '1.23', '1.22']
  requirements: []
  incompatibilities: []
- version: 1.3.1
  kube: ['1.24', '1.23', '1.22', '1.21', '1.20']
  requirements: []
  incompatibilities: []
- version: 1.3.0
  kube: ['1.24', '1.23', '1.22', '1.21', '1.20']
  requirements: []
  incompatibilities: []