icon: https://github.com/pluralsh/plural-artifacts/blob/main/ingress-nginx/plural/icons/nginx.png?raw=true
git_url: https://github.com/kubernetes/ingress-nginx
release_url: https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v{vsn}
helm_repository_url: https://kubernetes.github.io/ingress-nginx
versions:
- version: 1.11.3
  kube: ['1.30', '1.29', '1.28', '1.27', '1.26']
  requirements: []
  incompatibilities: []
  chart_version: 4.11.3
- version: 1.10.1
  kube: ['1.30', '1.29', '1.28', '1.27', '1.26']
  requirements: []
  incompatibilities: []
  chart_version: 4.10.1
- version: 1.10.0
  kube: ['1.29', '1.28', '1.27', '1.26']
  requirements: []
  incompatibilities: []
  chart_version: 4.10.0
- version: 1.9.6
  kube: ['1.29', '1.28', '1.27', '1.26', '1.25']
  requirements: []
  incompatibilities: []
  chart_version: 4.9.1
- version: 1.9.0
  kube: ['1.28', '1.27', '1.26', '1.25']
  requirements: []
  incompatibilities: []
  chart_version: 4.8.0
- version: 1.7.1
  kube: ['1.27', '1.26', '1.25', '1.24']
  requirements: []
  incompatibilities: []
  chart_version: 4.6.1
- version: 1.6.4
  kube: ['1.26', '1.25', '1.24', '1.23']
  requirements: []
  incompatibilities: []
  chart_version: 4.5.2
- version: 1.5.1
  kube: ['1.25', '1.24', '1.23']
  requirements: []
  incompatibilities: []
  chart_version: 4.4.0
- version: 1.4.0
  kube: ['1.25', '1.24', '1.23', '1.22']
  requirements: []
  incompatibilities: []
  chart_version: 4.3.0
- version: 1.3.1
  kube: ['1.24', '1.23', '1.22', '1.21', '1.20']
  requirements: []
  incompatibilities: []
  chart_version: 4.2.4
