icon: https://github.com/pluralsh/plural-artifacts/blob/main/monitoring/plural/icons/monitoring.png?raw=true
git_url: https://github.com/prometheus-community/helm-charts
release_url: https://github.com/prometheus-community/helm-charts/releases/tag/kube-prometheus-stack-{vsn}
readme_url: https://raw.githubusercontent.com/prometheus-community/helm-charts/main/charts/kube-prometheus-stack/README.md
helm_repository_url: https://prometheus-community.github.io/helm-charts
versions:
- version: 79.8.2
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25']
  chart_version: 79.8.2
  images: []
  requirements: []
  incompatibilities: []
- version: 78.5.0
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25']
  chart_version: 78.5.0
  images: []
  requirements: []
  incompatibilities: []
- version: 77.14.0
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25']
  chart_version: 77.14.0
  images: []
  requirements: []
  incompatibilities: []
- version: 76.5.1
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25']
  chart_version: 76.5.1
  images: []
  requirements: []
  incompatibilities: []
- version: 75.18.1
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25']
  chart_version: 75.18.1
  images: []
  requirements: []
  incompatibilities: []
- version: 74.2.2
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25']
  chart_version: 74.2.2
  images: []
  requirements: []
  incompatibilities: []
- version: 73.2.3
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25']
  chart_version: 73.2.3
  images: []
  requirements: []
  incompatibilities: []
- version: 72.9.1
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25',
    '1.24', '1.23', '1.22', '1.21', '1.20', '1.19']
  chart_version: 72.9.1
  images: []
  requirements: []
  incompatibilities: []
- version: 71.2.0
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25',
    '1.24', '1.23', '1.22', '1.21', '1.20', '1.19']
  chart_version: 71.2.0
  images: []
  requirements: []
  incompatibilities: []
- version: 70.10.0
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25',
    '1.24', '1.23', '1.22', '1.21', '1.20', '1.19']
  chart_version: 70.10.0
  images: []
  requirements: []
  incompatibilities: []
- version: 69.8.2
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25',
    '1.24', '1.23', '1.22', '1.21', '1.20', '1.19']
  chart_version: 69.8.2
  images: []
  requirements: []
  incompatibilities: []
- version: 68.5.0
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25',
    '1.24', '1.23', '1.22', '1.21', '1.20', '1.19']
  chart_version: 68.5.0
  images: []
  requirements: []
  incompatibilities: []
- version: 67.11.0
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25',
    '1.24', '1.23', '1.22', '1.21', '1.20', '1.19']
  chart_version: 67.11.0
  images: []
  requirements: []
  incompatibilities: []
- version: 66.7.1
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25',
    '1.24', '1.23', '1.22', '1.21', '1.20', '1.19']
  chart_version: 66.7.1
  images: []
  requirements: []
  incompatibilities: []
- version: 65.8.1
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25',
    '1.24', '1.23', '1.22', '1.21', '1.20', '1.19']
  chart_version: 65.8.1
  images: []
  requirements: []
  incompatibilities: []
- version: 64.0.0
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25',
    '1.24', '1.23', '1.22', '1.21', '1.20', '1.19']
  chart_version: 64.0.0
  images: []
  requirements: []
  incompatibilities: []
- version: 63.1.0
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25',
    '1.24', '1.23', '1.22', '1.21', '1.20', '1.19']
  chart_version: 63.1.0
  images: []
  requirements: []
  incompatibilities: []
- version: 62.7.0
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25',
    '1.24', '1.23', '1.22', '1.21', '1.20', '1.19']
  chart_version: 62.7.0
  images: []
  requirements: []
  incompatibilities: []
- version: 61.9.0
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25',
    '1.24', '1.23', '1.22', '1.21', '1.20', '1.19']
  chart_version: 61.9.0
  images: []
  requirements: []
  incompatibilities: []
- version: 60.5.0
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25',
    '1.24', '1.23', '1.22', '1.21', '1.20', '1.19']
  chart_version: 60.5.0
  images: []
  requirements: []
  incompatibilities: []
- version: 59.1.0
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25',
    '1.24', '1.23', '1.22', '1.21', '1.20', '1.19']
  chart_version: 59.1.0
  images: []
  requirements: []
  incompatibilities: []
- version: 58.7.2
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25',
    '1.24', '1.23', '1.22', '1.21', '1.20', '1.19']
  chart_version: 58.7.2
  images: []
  requirements: []
  incompatibilities: []
- version: 57.2.1
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25',
    '1.24', '1.23', '1.22', '1.21', '1.20', '1.19']
  chart_version: 57.2.1
  images: []
  requirements: []
  incompatibilities: []
- version: 56.21.4
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25',
    '1.24', '1.23', '1.22', '1.21', '1.20', '1.19']
  chart_version: 56.21.4
  images: []
  requirements: []
  incompatibilities: []
- version: 55.11.0
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25',
    '1.24', '1.23', '1.22', '1.21', '1.20', '1.19']
  chart_version: 55.11.0
  images: []
  requirements: []
  incompatibilities: []
- version: 54.2.2
  kube: ['1.34', '1.33', '1.32', '1.31', '1.30', '1.29', '1.28', '1.27', '1.26', '1.25',
    '1.24', '1.23', '1.22', '1.21', '1.20', '1.19']
  chart_version: 54.2.2
  images: []
  requirements: []
  incompatibilities: []
