icon: https://github.com/pluralsh/plural-artifacts/blob/main/monitoring/plural/icons/monitoring.png?raw=true
git_url: https://github.com/prometheus-community/helm-charts
release_url: https://github.com/prometheus-community/helm-charts/releases/tag/kube-prometheus-stack-{vsn}
readme_url: https://raw.githubusercontent.com/prometheus-community/helm-charts/main/charts/kube-prometheus-stack/README.md
helm_repository_url: https://prometheus-community.github.io/helm-charts
versions:
- version: 54.0.0
  kube: ['1.28', '1.27', '1.26', '1.25', '1.24', '1.23', '1.22', '1.21', '1.20', '1.19']
  requirements: []
  incompatibilities: []
- version: 50.0.0
  kube: ['1.28', '1.27', '1.26', '1.25', '1.24', '1.23', '1.22', '1.21', '1.20', '1.19']
  requirements: []
  incompatibilities: []
- version: 27.0.0
  kube: ['1.24', '1.23', '1.22', '1.21', '1.20', '1.19']
  requirements: []
  incompatibilities: []
- version: 15.2.2
  kube: ['1.24', '1.23', '1.22', '1.21', '1.20', '1.19']
  requirements: []
  incompatibilities: []
- version: 0.0.0
  kube: ['1.21', '1.20', '1.19', '1.18', '1.17', '1.16']
  requirements: []
  incompatibilities: []
