icon: https://github.com/traefik/traefik/raw/master/docs/content/assets/img/traefik.logo-dark.png
git_url: https://github.com/traefik/traefik
release_url: https://github.com/traefik/traefik/releases/tag/v{vsn}
helm_repository_url: https://traefik.github.io/charts
versions:
- version: 3.3.4
  kube: ['1.32', '1.31', '1.30', '1.29']
  requirements: []
  incompatibilities: []
  chart_version: 34.4.1
- version: 3.1.4
  kube: ['1.32', '1.31', '1.30', '1.29']
  requirements: []
  incompatibilities: []
  chart_version: 31.1.1
- version: 3.1.3
  kube: ['1.31', '1.30', '1.29']
  requirements: []
  incompatibilities: []
  chart_version: 31.1.0
- version: 3.0.2
  kube: ['1.31', '1.30', '1.29', '1.28']
  requirements: []
  incompatibilities: []
  chart_version: 28.3.0
- version: 2.11.10
  kube: ['1.32', '1.31', '1.30', '1.29']
  requirements: []
  incompatibilities: []
- version: 2.11.4
  kube: ['1.31', '1.30', '1.29', '1.28']
  requirements: []
  incompatibilities: []
- version: 2.10.3
  kube: ['1.30', '1.29', '1.28']
  requirements: []
  incompatibilities: []
