icon: https://github.com/traefik/traefik/raw/master/docs/content/assets/img/traefik.logo-dark.png
git_url: https://github.com/traefik/traefik
release_url: https://github.com/traefik/traefik/releases/tag/v{vsn}
helm_repository_url: https://traefik.github.io/charts
versions:
- version: 3.2.1
  kube: ['1.31', '1.30', '1.29', '1.28']
  requirements: []
  incompatibilities: []
  chart_version: 33.1.0-rc1
- version: 3.1.3
  kube: ['1.31', '1.30', '1.29']
  requirements: []
  incompatibilities: []
  chart_version: 31.1.0
- version: 3.0.4
  kube: ['1.31', '1.30', '1.29', '1.28']
  requirements: []
  incompatibilities: []
  chart_version: 29.0.0
- version: 2.11.14
  kube: ['1.31', '1.30', '1.29', '1.28']
  requirements: []
  incompatibilities: []
- version: 2.10.3
  kube: ['1.30', '1.29', '1.28']
  requirements: []
  incompatibilities: []
