apiVersion: deployments.plural.sh/v1alpha1
kind: CustomCompatibilityMatrix
metadata:
  labels:
    app.kubernetes.io/name: customcompatibilitymatrix
    app.kubernetes.io/instance: customcompatibilitymatrix-sample
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: controller
  name: customcompatibilitymatrix-sample
spec:
  # TODO(user): Add fields here
