apiVersion: deployments.plural.sh/v1alpha1
kind: CustomCompatibilityMatrix
metadata:
  labels:
    app.kubernetes.io/name: customcompatibilitymatrix
    app.kubernetes.io/instance: customcompatibilitymatrix-sample
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: controller
  name: customcompatibilitymatrix-sample
spec:
  icon: https://velero.io/img/Velero.svg
  gitUrl: https://github.com/vmware-tanzu/velero
  releaseUrl: https://github.com/vmware-tanzu/velero/releases/tag/v{vsn}
  versions:
    - version: v1.5.4
      chartVersion: 2.22.1
      kube:
        - "1.35"
        - "1.34"
      summary:
        helmChanges:
          - "Added support for AWS EBS CSI driver"
        breakingChanges:
          - "Removed support for AWS EBS CSI driver"