apiVersion: deployments.plural.sh/v1alpha1
kind: UpgradePlanCallout
metadata:
  labels:
    app.kubernetes.io/name: upgradeplancallout
    app.kubernetes.io/instance: upgradeplancallout-sample
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: controller
  name: upgradeplancallout-sample
spec:
  # TODO(user): Add fields here
