apiVersion: v1
kind: Namespace
metadata:
  name: terratest
  labels:
    environment: dev
    team: platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: full-access
  namespace: terratest
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: full-access-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: full-access
    namespace: terratest
---
apiVersion: deployments.plural.sh/v1alpha1
kind: Sentinel
metadata:
  labels:
    app.kubernetes.io/name: sentinel
    app.kubernetes.io/instance: sentinel-sample
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: controller
  name: sentinel-terratest
  namespace: default
spec:
  name: terratest-git
  description: "test sentinel for terratest"
  checks:
    - type: INTEGRATION_TEST
      name: test-integration
      configuration:
        integrationTest:
          format: JUNIT
          repositoryRef:
            name: terratest-git
            namespace: default
          git:
            ref: main
            folder: "/"
          jobSpec:
            namespace: terratest
            serviceAccount: full-access
            containers:
              - image: ghcr.io/pluralsh/sentinel-harness:sha-b8d4540-terratest-0.51.0
---
apiVersion: deployments.plural.sh/v1alpha1
kind: GitRepository
metadata:
  name: terratest-git
  namespace: default
spec:
  url: https://github.com/pluralsh/terratest-suite.git