apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: k8saws
  namespace: default
spec:
  version: 0.0.1
  git:
    folder: nginx
    ref: master
    url: https://github.com/zreigz/k8s-helm.git
  clusterRef: {}
  cluster: mgmt
---
apiVersion: deployments.plural.sh/v1alpha1
kind: ManagedNamespace
metadata:
  labels:
    app.kubernetes.io/name: managednamespace
    app.kubernetes.io/instance: managednamespace-sample
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: controller
  name: managednamespace-sample-test
spec:
  name: test-sample
  service:
    name: k8saws
    namespace: default
  labels:
    name: test
  annotations:
    name: test
    app.kubernetes.io/created-by: controller
  target:
    distro: EKS
    tags:
      abc: "123"
      ads: "234"
