apiVersion: deployments.plural.sh/v1alpha1
kind: ManagedNamespace
metadata:
  labels:
    app.kubernetes.io/name: managednamespace
    app.kubernetes.io/instance: managednamespace-sample
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: controller
  name: managednamespace-sample
spec:
  name: test-sample
  service:
    name: k8saws
    namespace: default
    git:
      folder: nginx
      ref: master
    repositoryUrl: https://github.com/zreigz/k8s-helm.git
  labels:
    name: test
  annotations:
    name: test
    app.kubernetes.io/created-by: controller
  target:
    distro: EKS
