apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "controller.fullname" . }}-manager-role
  labels:
    app.kubernetes.io/part-of: plural-deployment-controller
  {{- include "controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - deployments.plural.sh
  resources:
  - clusterrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.plural.sh
  resources:
  - clusterrestores/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - clusterrestores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - clusterrestoretriggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.plural.sh
  resources:
  - clusterrestoretriggers/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - clusterrestoretriggers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.plural.sh
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - customstackruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.plural.sh
  resources:
  - customstackruns/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - customstackruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - deploymentsettings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.plural.sh
  resources:
  - deploymentsettings/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - deploymentsettings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - gitrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.plural.sh
  resources:
  - gitrepositories/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - gitrepositories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - globalservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.plural.sh
  resources:
  - globalservices/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - globalservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - infrastructurestacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.plural.sh
  resources:
  - infrastructurestacks/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - infrastructurestacks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - managednamespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.plural.sh
  resources:
  - managednamespaces/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - managednamespaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - notificationrouters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.plural.sh
  resources:
  - notificationrouters/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - notificationrouters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - notificationsinks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.plural.sh
  resources:
  - notificationsinks/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - notificationsinks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - pipelinecontexts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.plural.sh
  resources:
  - pipelinecontexts/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - pipelinecontexts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - pipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.plural.sh
  resources:
  - pipelines/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - pipelines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - prautomations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.plural.sh
  resources:
  - prautomations/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - prautomations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - prautomationtriggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.plural.sh
  resources:
  - prautomationtriggers/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - prautomationtriggers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.plural.sh
  resources:
  - projects/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - projects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - providers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.plural.sh
  resources:
  - providers/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - providers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - scmconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.plural.sh
  resources:
  - scmconnections/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - scmconnections/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - servicedeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.plural.sh
  resources:
  - servicedeployments/finalizers
  verbs:
  - update
- apiGroups:
  - deployments.plural.sh
  resources:
  - servicedeployments/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "controller.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/part-of: plural-deployment-controller
  {{- include "controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "controller.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "controller.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'