name: CI / Nexus

on:
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/nexus-ci.yaml"
      - "go/nexus/**"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go/nexus/go.mod

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          working-directory: go/nexus

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go/nexus/go.mod

      - name: Run tests
        run: make test
        working-directory: go/nexus

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go/nexus/go.mod

      - name: Build binary
        run: make build
        working-directory: go/nexus

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: go/nexus
          file: ./Dockerfile
          push: false
          tags: ghcr.io/pluralsh/nexus:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

